### ISSUE TITLE
Tool doesn't work for non-cloned sites

### ISSUE THREAD

**Issue by J16053** [comnetsAD/JS_Analyzer#8]
Issue creating the corresponding .h file for new websites not in proxy/data/

**Comment by yzaki** [comment]
I think I have fixed the problem. Can you give it a try? 
Before you try make sure to delete all entries in the DB first, because I have removed the :443 from the saved URL keys

**Comment by J16053** [comment]
Should I just clear my entire DB then? i.e. TRUNCATE TABLE caching;

**Comment by J16053** [comment]
It seems to work now! I ran into a bunch of other errors while testing different sites but I'll make separate issues for those.
![image](https://user-images.githubusercontent.com/24278937/65410181-c056fe80-ddfa-11e9-89ef-83a6c3943394.png)
