### ISSUE TITLE
Non-utf-8 character sets

### ISSUE THREAD

**Issue by J16053** [comnetsAD/JS_Analyzer#9]
Something to look into as we go into the top 500 sites: character encoding differs across languages and websites (and many of top 500 will be in Chinese)
![image](https://user-images.githubusercontent.com/24278937/65409747-9224ef00-ddf9-11e9-8d8f-06f9260648b9.png)

**Comment by yzaki** [comment]
Yes I know about this. Should be an easy fix. 
Let me add it

-----
Yasir Zaki
Assistant Professor of Computer Science
NYU Abu Dhabi
Computational Research Building (A2)
Office Number 191
Office Tel (UAE): +971 2 628 4860

NYU Abu Dhabi, Saadiyat Campus
P.O. Box 129188
Abu Dhabi, United Arab Emirates

**Comment by yzaki** [comment]
I added the default encoding of utf-8. Can you please test it with the same website that was causing the issue?

**Comment by J16053** [comment]
It still doesn't work when I test it with Autohome.com.cn (top site #492)

**Comment by yzaki** [comment]
I think I fixed it now. In addition to another weird issue we were having with the Autohome.com.cn webpage.
Can you please test it?

**Comment by J16053** [comment]
Yes, looks great now!
